# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.



title: 刘浩然 香港中文大学会计学院
description: >- # this means to ignore newlines until "baseurl:"
  刘浩然(中文主页).
# baseurl: "/Lin" # the subpath of the site  #bay
url: "https://leightonliu.github.io" # the base hostname & protocol for the site
og_image: /assets/img/profile-pic.jpg
#google_analytics: "UA-121636368-3"

header: 
  pages:
    - name: Home
      slug: /
   # - name: CV
   #- name: Research

footer:
  show_powered_by: false
  # contact:
  #   - name: Email
  #     value: haoran.liu@link.cuhk.edu.hk
  #     link: mailto:haoran.liu@link.cuhk.edu.hk
  # follow:
  #   - name: LinkedIn
  #     link: www.linkedin.com/in/haoran-leighton-liu/


# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
